// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using React.ExternalAPI.Server.Models;

#nullable disable

namespace React.ExternalAPI.Server.Migrations
{
    [DbContext(typeof(HitterContext))]
    partial class HitterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("React.ExternalAPI.Server.Models.Hitter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("BattingAverage")
                        .HasColumnType("float");

                    b.Property<int>("HomeRuns")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OnBasePercentage")
                        .HasColumnType("float");

                    b.Property<int>("RunsBattedIn")
                        .HasColumnType("int");

                    b.Property<double>("SluggingPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hitters");
                });
#pragma warning restore 612, 618
        }
    }
}
