// <auto-generated />
using ExternalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExternalAPI.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20240115194441_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExternalAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Nissan Skyline R34 GT-R is an iconic Japanese sports car renowned for its potent twin-turbo inline-six and timeless design. The Toyota Supra MK4, featuring the legendary 2JZ engine, stands as a symbol of high-performance excellence and distinctive styling in automotive history.",
                            Hp = 500,
                            ImageUrl = "https://speedhunters-wp-production.s3.amazonaws.com/wp-content/uploads/2021/07/20205450/Speedhunters_R34roller-3-1200x800.jpg",
                            Make = "Nissan",
                            Model = "Skyline R34 GT-R",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_Skyline_GT-R",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Nissan 350Z delivers a thrilling driving experience with its powerful V6 engine and rear-wheel-drive configuration, while its sleek design and bold curves contribute to its enduring appeal as a modern classic in the world of sports cars.",
                            Hp = 300,
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/350rear-1513348241.jpeg",
                            Make = "Nissan",
                            Model = "350Z",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_350Z",
                            YearOfRelease = 1995
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Nissan 200SX, part of the S platform series, is a compact and sporty coupe celebrated for its agile handling and varied engine options, offering a balance of power and efficiency. Recognized for its sleek, aerodynamic design, the 200SX remains a beloved choice among enthusiasts for its sporty appeal and tunable capabilities.",
                            Hp = 400,
                            ImageUrl = "https://i.redd.it/tudob7j67ev41.jpg",
                            Make = "Nissan",
                            Model = "200sx",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_200SX",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Toyota Supra MK4, an automotive legend, is distinguished by its powerful 2JZ inline-six engine, rear-wheel-drive layout, and iconic styling. Renowned for its exceptional performance on both the street and the racetrack, the Supra MK4 has achieved cult status among enthusiasts for its cutting-edge technology and enduring appeal.",
                            Hp = 1200,
                            ImageUrl = "https://ronbrooks.b-cdn.net/wp-content/uploads/2023/06/toyota-supra-mk4.png",
                            Make = "Toyota",
                            Model = "Supra MK4",
                            WikiLink = "https://en.wikipedia.org/wiki/Toyota_Supra",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Toyota AE86, a compact and nimble sports car, is celebrated for its lightweight chassis and agile handling, particularly in drifting culture. Part of the Corolla Levin and Sprinter Trueno lineup, the AE86's iconic design and association with motorsports have solidified its status as a cult classic among automotive enthusiasts.",
                            Hp = 180,
                            ImageUrl = "https://cdn.arstechnica.net/wp-content/uploads/2023/01/20230113_01_01_s.jpg",
                            Make = "Toytoa",
                            Model = "Sprinter Trueno AE86",
                            WikiLink = "https://en.wikipedia.org/wiki/Toyota_AE86",
                            YearOfRelease = 1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
