// <auto-generated />
using ExternalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExternalAPI.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20240115193030_AdditionalData")]
    partial class AdditionalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExternalAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Skyline R34 GT-R is an iconic Japanese sports car celebrated for its powerful performance and sleek design. Equipped with a twin-turbocharged inline-six engine, advanced all-wheel-drive system, and distinctive body styling, the R34 is revered among automotive enthusiasts for its dominance on the track and timeless appeal. Its legendary status is further solidified by its starring role in motorsport and popular culture.",
                            Hp = 500,
                            ImageUrl = "https://speedhunters-wp-production.s3.amazonaws.com/wp-content/uploads/2021/07/20205450/Speedhunters_R34roller-3-1200x800.jpg",
                            Make = "Nissan",
                            Model = "Skyline R34 GT-R",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_Skyline_GT-R",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Nissan 350Z is a dynamic and stylish sports car that gained popularity for its engaging driving experience. With a potent V6 engine, rear-wheel drive, and a well-tuned suspension, the 350Z delivers a thrilling performance. Its distinctive design, characterized by a sleek profile and bold curves, contributes to its enduring appeal as a modern classic in the automotive world.",
                            Hp = 300,
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/350rear-1513348241.jpeg",
                            Make = "Nissan",
                            Model = "350Z",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_350Z",
                            YearOfRelease = 1995
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Nissan 200SX, part of the S platform series, is a compact and sporty coupe that gained acclaim for its agile handling and performance. With a focus on rear-wheel drive dynamics, it featured various engine options over its production years, delivering a balance of power and efficiency. Recognized for its sleek and aerodynamic design, the Nissan 200SX remains a beloved choice among enthusiasts for its sporty appeal and tunable capabilities.",
                            Hp = 400,
                            ImageUrl = "https://i.redd.it/tudob7j67ev41.jpg",
                            Make = "Nissan",
                            Model = "200sx",
                            WikiLink = "https://en.wikipedia.org/wiki/Nissan_200SX",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Toyota Supra MK4, an automotive legend, is a high-performance sports car celebrated for its powerful 2JZ inline-six engine, rear-wheel-drive layout, and iconic styling. Renowned for its prowess on both the street and the racetrack, the Supra MK4 has achieved cult status among enthusiasts. Its combination of cutting-edge technology, striking design, and exceptional performance has solidified its place as one of the most revered and sought-after sports cars in automotive history.",
                            Hp = 1200,
                            ImageUrl = "https://ronbrooks.b-cdn.net/wp-content/uploads/2023/06/toyota-supra-mk4.png",
                            Make = "Toyota",
                            Model = "Supra MK4",
                            WikiLink = "https://en.wikipedia.org/wiki/Toyota_Supra",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Toyota AE86, a cult classic, is a compact rear-wheel-drive sports car celebrated for its lightweight chassis and nimble handling. Produced in the mid-1980s, it gained fame through motorsports, particularly in drifting. The AE86, part of the Corolla Levin and Sprinter Trueno lineup, is powered by a 4A-GE engine, and its iconic pop-up headlights and timeless design contribute to its enduring popularity among automotive enthusiasts.",
                            Hp = 180,
                            ImageUrl = "https://cdn.arstechnica.net/wp-content/uploads/2023/01/20230113_01_01_s.jpg",
                            Make = "Toytoa",
                            Model = "Sprinter Trueno AE86",
                            WikiLink = "https://en.wikipedia.org/wiki/Toyota_AE86",
                            YearOfRelease = 1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
